export const electronicsProjectsList = [
  "Solar Peizo Hybrid Power Charging System",
  "Zigbee Based Room Temperature Controller Project",
  "Load Sensing Seats With Lights Fan Control",
  "Secure Fingerprint Bank Locker With Image Capture",
  "Accurate Room Temperature Controller Project",
  "High Performance Hovercraft With Power Turning",
  "Smart Solar Grass Cutter With Lawn Coverage",
  "PC Based Home Automation",
  "Advanced Military Spying & Bomb Disposal Robot",
  "Human Speed Detection Project",
  "Hovercraft Controlled By Android",
  "Fully Automated Solar Grass Cutter",
  "Machine Overheat Detection With Alert",
  "Rf Controlled Spy Robot With Night Vision Camera",
  "GSM based Industry Protection System",
  "Automated Visitor Counter With 7 Segment Display",
  "Vehicle Theft Detection/Notification With Remote Engine Locking",
  "Automated Elevator With Overload Alert",
  "Accurate Room Temperature Controller Project",
  "Gsm Based Weather Reporting (Temperature/Light/Humidity)",
  "Fingerprint Authenticated Device Switcher",
  "Fingerprint Based Exam Hall Authentication",
  "Zigbee based Wireless Home Security System",
  "Intelligent Surveillance and Night Patrolling Drone",
  "Automatic Waste Segregation System",
  "Arduino based Snake Robot Controlled using Android Application",
  "Garbage Collection Robot Using Wireless Communication Technology",
  "Smart Door Receptionist with Smart Lock",
  "Auto Selection of any Available Phase in 3 Phase Supply System",
  "ACPWM Control System for Induction Motor using AVR Microcontroller",
  "Greenhouse Monitoring and Control System using IOT Project",
  "IOT Based Coal Mine Safety Monitoring and Alerting System",
  "Advanced Automatic Self-Car Parking using Arduino Project",
  "IOT Based Heart Monitoring System Using ECG",
  "Smart Stand-up wheelchair using Raspberry Pi & RF",
  "Arduino Based Autonomous Fire Fighting Robot",
  "Dual Axis Solar Tracking System with Weather Sensor",
  "Android Controlled Automobile",
  "Home Automation Using Android",
  "Zigbee Based Secure Wireless Communication Using AES",
  "Voice Controlled Robotic Vehicle",
  "Pesticide Sprayer Spider Robot with Grass Cutter",
  "Smart Shopping Trolley that Follows Customer",
  "IR Wireless Underwater Communication System",
  "Advanced Footstep Power Generation System using RFID for Charging",
  "Induction Motor Speed Controller Project",
  "Arduino Alcohol Sense Engine Lock",
  "Arduino Covid Disinfection Box",
  "Arduino Based System To Measure Solar Power",
  "Hybrid Inverter With Solar Battery Charging",
  "Fingerprint Based Bank Locker System",
  "Face Recognition Door Lock System Using Raspberry Pi",
  "Prepaid Energy Meter With Theft Detection",
  "Programmable Omni Direction Robotic Arm Vehicle",
  "Smart Room Temperature Controller Atmega",
  "Ultrasonic Radar Project",
  "IOT Irrigation Monitoring & Controller System",
  "Car Safety System With Airbag Notification",
  "Automatic Noise Level Monitor & Controller System",
  "Induction Motor Controller and Protection System",
  "IOT Covid Patient Health Monitor in Quarantine",
  "Smart Wireless Battery Charging With Charge Monitor Project",
  "DIY Bluetooth Gamepad for Android Gaming",
  "IOT Circuit Breaker Project",
  "Third Eye For Blind Ultrasonic Vibrator Glove",
  "Automatic Road Reflector Light",
  "Arduino Ultrasonic Sonar/Radar Monitor Project",
  "Remote Control Plant Watering System Using 8051",
  "Women Safety Night Patrolling Robot",
  "IOT Mining Tracking & Worker Safety Helmet",
  "Auto Baby Cry Detector Sleep Music Player PIC",
  "Auto Water Pump Switcher",
  "Auto Billing Mall Shopping Cart 8051",
  "IOT Flood Monitoring & Alerting System Using Ras Pi",
  "EV BMS With Charge Monitor and Fire Protection",
  "IOT Garbage Monitoring Using Raspberry Pi",
  "Fingerprint Vehicle Starter Project",
  "TV Remote Controlled Home Automation PIC",
  "IOT Based ICU Patient Monitoring System",
  "Motion Based Door Opener With Metal Detector",
  "Automatic Light Intensity Controller By External Light Sensing",
  "Vehicle Movement Based Street Lights With External Light Sensing",
  "Traffic Density Control With Android Override Using Avr",
  "Alcohol Sensing Alert with Engine Locking Project",
  "DIY Power Bank with Plasma Lighter",
  "Path Planner Robot for Indoor Positioning",
  "Wifi Based Secure Wireless Communication Using RSA",
  "IOT Car Parking System",
  "Solar Powered Battery Charging With Reverse Current Protection",
  "Multi Robot Coordination For Swarm Robotics",
  "Wearable Health Monitoring System Project",
  "Automated Night Lighting System",
  "Zigbee Based Gas Fire Detection System",
  "Short Circuit Indicator Project",
  "Sun Tracking Solar Panel Using Arduino",
  "Object Tracker & Follower Robot Using Raspberry Pi",
  "IOT Smart Energy Grid",
  "Bill Prediction & Power Factor Measuring With SMS Alert",
  "Car Accident & Alcohol Detector & Recorder Blackbox",
  "IOT Weather Reporting System using Adruino and Ras Pi",
  "Lifi Data Transfer System",
  "Ultrasonic Glasses For the Blind",
  "Social Distancing ID Card",
  "Industrial Production Line Counter System",
  "Pocket Piano Using 555 Timer IC",
  "Arduino Powered MP3 Player",
  "Portable PM10 PM2.5 Pollution Analyzer",
  "Smart Digital SchoolBell With Timetable Display",
  "Arduino Stepper Motor Controller",
  "Industrial Production Target Counter Display System",
  "Stop and Go Queue Entry Manager System",
  "Digital Car Turning and Braking Indicator",
  "RFID Token Based Appointment Calling System",
  "Digital Nameplate with Visitor Sensing",
  "Wearable Computer With Temperature Distance Sensors",
  "Weather Imaging CubeSat with Telemetry Transmission",
  "Ebike Speed Controller System",
  "Air Water Pollution Sensing Smart Watch",
  "Solar SeaWeather and Pollution Transmitter Buoy",
  "Coin Operated Water ATM with Bottle Dispenser",
  "Wearable Oscilloscope Smart Watch",
  "Contactless Switch For 4 Load Switching",
  "Smart Vehicle Headlight Auto Switching",
  "Contactless Gesture Controlled Study Lamp",
  "Earthquake Monitor and Alerting System",
  "3D Scanner Machine using Arduino",
  "4 Slot Coin Operated Cola Vending Machine",
  "Mobile Phone & Cash UV Disinfector for COVID",
  "8 Leg Spider Robot by Theo Jansen Linkage",
  "IOT IV Bag Monitoring and Alert System",
  "Portable Induction Cooktop With Time/Temp Settings",
  "Barcode Scanner & Display using Arduino",
  "Electromagnetic Coil Gun 3 Stage",
  "Gesture Control Bicycle Indicator Gloves",
  "Wireless Master Joystick Controller for Robotics",
  "Automatic Coil Winding Machine",
  "Waterproof Action Camera Drone",
  "IOT Water Pollution Monitor RC Boat",
  "Voice Controlled Air Purifier",
  "Automatic Hydroponic Plant Grow Pot",
  "Video Calling/Recording Smartphone Stand",
  "Solar Power Bank with Wireless Charging",
  "Gesture Control Bluetooth Speaker",
  "Rain Sensing Hands Free Umbrella Bag",
  "LIDAR Micro Done With Proximity Sensing",
  "Contactless IOT Doorbell",
  "RC Underwater Exploration Drone",
  "Android Powered Juice Vending Machine",
  "IOT Smart Parking Using RFID",
  "IOT Syringe Infusion Pump",
  "Programmable Robotic Arm Using Arduino",
  "IOT Virtual Doctor Robot",
  "COVID-19 Vaccine Cold Storage Box",
  "IOT Weather Station Airship",
  "Solar Floor Cleaner Robot",
  "Arduino Multi Player Air Hockey Table",
  "Indoor Racing Drone with Action Camera",
  "DIY Tricopter Selfie Drone",
  "Automatic Wire Cutter And Stripper Machine",
  "360° Aerial Surveillance UAV With IOT Camera",
  "360° Filmmaking Drone For 4K HD Video",
  "Solar Outdoor Air Purifier & Air Quality Monitor",
  "Fire Extinguisher & Fire Fighting Drone",
  "IOT Garbage Segregator & Bin Level Indicator",
  "Fog Disinfection Handwash Machine To Save Water",
  "IOT Temperature & Mask Scan Entry System",
  "Semi Automatic Back Massager Machine",
  "Indoor Farming Hydroponic Plant Grow Chamber",
  "Portable PPE Kit Sterilizer Ozone + UV",
  "Thermal Screening Drone",
  "IOT Contactless Covid Testing Booth Automation",
  "Floating Sun Tracker Hydraulic Solar Panel",
  "AI Bartender Cocktail Maker Machine",
  "IOT Dog Daycare Robot",
  "IOT Social Distancing & Monitoring Robot For Queue",
  "Dual Mount Auto Sanitizer Dispenser",
  "Auto Indoor Hydroponic Fodder Grow Chamber",
  "Autonomous Theft Proof Delivery Robot For Food & Ecommerce",
  "Social Distancing & Mask Monitor Drone",
  "DIY Oxygen Concentrator Generator For Covid 19",
  "DIY Ventilator using Arduino For Covid Pandemic",
  "Auto Temperature Detector for Entrance For Covid Safety",
  "Waste and Garbage Recycling Vending Machine Project",
  "Raspberry Pi Based Vehicle Starter on Face Detection",
  "Gas Leakage Detection with Buzzer System using Atmega",
  "Water Pollution Monitoring RC Boat",
  "Multi-purpose Sea Surveillance + Search & Rescue RC Boat",
  "Raspberry Pi Vehicle Anti-Theft Face Recognition System",
  "Home Air Quality Monitoring System Project",
  "Voice Based Hot Cold-Water Dispenser System using Ras Pi",
  "Rotating Solar Inverter Project using Microcontroller 50W",
  "Vertical Axis Wind Turbine With Inverter",
  "Raspberry Pi based Weather Reporting Over IOT",
  "IOT Based Monitoring System for Comatose Patients",
  "Motion Controlled Pick & Place Obstacle Avoider Robot",
  "IOT Early Flood Detection & Avoidance",
  "IOT Prison Break Monitoring & Alerting System",
  "Plant Soil Moisture & Ph Sensing Alarm Using 8051",
  "Smart Crop Protection System From Animals PIC",
  "IOT Paralysis Patient Health Care Project",
  "RFID Based Smart Master Card For Bus Train Metro Ticketing",
  "Induction Motor Speed & Direction Controller",
  "DC Motor Speed Control Using GSM",
  "Mini Windmill Power Generation Project",
  "Raspberry Pi Wheelchair With Safety System",
  "Multiple Cities Load Shedding Using ARM",
  "Automatic Lemon Juice Vending Machine",
  "Rain Sensing Automatic Car Wiper",
  "Wireless Red Signal Alerting For Trains"
];
