export const instrumentationProjectsList = [
  "Weather Imaging CubeSat with Telemetry Transmission",
  "Ebike Speed Controller System",
  "Air Water Pollution Sensing Smart Watch",
  "Solar SeaWeather and Pollution Transmitter Buoy",
  "Coin Operated Water ATM with Bottle Dispenser",
  "Cam Shaft Mechanism DIY Ventilator",
  "Wearable Oscilloscope Smart Watch",
  "Contactless Switch For 4 Load Switching",
  "Smart Vehicle Headlight Auto Switching",
  "Contactless Gesture Controlled Study Lamp",
  "Earthquake Monitor and Alerting System",
  "3D Scanner Machine using Arduino",
  "Contactless Air Conveyor For Goods Movement",
  "Hydraulic Flood Protection System for Homes",
  "4 Slot Coin Operated Cola Vending Machine",
  "Auto Dough Maker Dough Kneading Machine",
  "Variable Head Solar Grass Cutter Weed Trimmer",
  "Head Tilt Controlled Wheelchair for Disabled",
  "Advanced Mosquito Killer Machine",
  "Portable Induction Cooktop With Time/Temp Settings",
  "Three Axis CNC Machine 1 Meter x 2 Meter",
  "RC Solar Lake Pool Cleaner Drone",
  "Electromagnetic Coil Gun 3 Stage",
  "Wireless Master Joystick Controller for Robotics",
  "Video Calling/Recording Smartphone Stand",
  "Rain Sensing Hands Free Umbrella Bag",
  "Auto IV Pole with IV Bag Refill Alert",
  "Programmable Robotic Arm Using Arduino",
  "Mattress Deep Cleaning Machine",
  "Solar Floor Cleaner Robot",
  "Wind & Solar Mobile Charging Station",
  "Floating Sun Tracker Hydraulic Solar Panel",
  "Automatic Liquid Dispenser Vending Machine",
  "PLC based Automatic Dam Shutter Control System",
  "PLC Based Smart Elevator Control System Project",
  "PLC Based Intelligent Traffic Control System using Sensors",
  "PLC Based Automatic Drainage Water Monitoring & Control System",
  "Airport Baggage Diverter System using QR",
  "PLC based Multi-channel Fire Detection & Alarm System Project",
  "Automatic Water Level Control System Using PLC Project",
  "Temperature Controller System Based on PLC Project",
  "PLC Based Sorting System Using Metal Detection",
  "PLC Based Paper Cutting Machine",
  "Automatic Stamping Labeling Machine Using PLC",
  "IOT Color Based Product Sorting Machine Project",
  "Power Meter billing Plus Load Control Using GSM",
  "Energy Management System With Programmable Numbers using GSM",
  "GSM based Industry Protection System",
  "Automatic Bottle Filling & Capping Machine Using PLC",
  "PLC Based Product Sorting Machine",
  "Water Recycling Car Wash System Using PLC",
  "Display Object Counter On 7 Segment Display",
  "Home Automation Using Touch Screen",
  "Auto Irrigation using soil moisture sensor",
  "Remote Controlled Robotic Arm Using Rf",
  "Efficient Power Manager Project",
  "Automated Visitor Counter With 7 Segment Display",
  "IR Based Obstacle Detection For Load Switching Project",
  "Automated Elevator With Overload Alert",
  "Industry Temperature Control System",
  "Industrial Load Switcher Based On Touch Screen",
  "Precise Digital Temperature Controller",
  "Motion Based Automatic Door Opener",
  "Alcohol Sensing Display With Alarm Project",
  "Home Automation Using Android",
  "Machine Overheat Detection With Alert",
  "Combustible Gas Detection With GSM Alert Using PIC",
  "Factory Worker Alcohol Detector With Automatic Machine Shutdown",
  "Gas Leak Detector With Automatic Air Exhaust Using ARM Cortex",
  "Solar Power Measurement System Using ARM Cortex",
  "Synchronized Multiple Motor Speed Controller Using ARM Cortex",
  "Multiple Load Controller For Industry Using ARM Cortex",
  "ARM Based Liquid Level Detection & Flow Control"
];
