export const mechanicalProjectsList = [
  "Air Powered Car Project",
  "Automatic Wire Cutter And Stripper Machine",
  "Spring Assist Peizo Generator",
  "Power Generator Pulley Rowing Machine",
  "Staircase Climbing Trolley",
  "Manual Roller Bending Machine",
  "3 Speed Gearbox Mechanism",
  "Remote Controlled Mini Forklift",
  "Sand Filter & Separator Project",
  "Springless Car Suspension Using Bevel Gears",
  "Mini Solar Water Heater",
  "Design and Fabrication of Pneumatic Vice Project",
  "Pneumatic Scissor Lift Jack Project",
  "Robotic Vehicle using Ackermann Steering Mechanism",
  "Six Legged Spider Bot using Klann Mechanism",
  "Levitating Frictionless Vertical Windmill",
  "360 Degree Fire Protection System",
  "Silent Air Purifier & Humidifier",
  "Goods Transport Stair Climber Robot",
  "Pneumatic Sheet Metal Cutting Machine",
  "Single Motor Double Door Opener Mechanism",
  "Auto Dough Maker Dough Kneading Machine",
  "Automatic Roti Puri Maker Motorized Press",
  "Wide Base 4 Wheel Steering Mechanism Chassis",
  "Contactless Air Conveyor For Goods Movement",
  "Electromagnetic Braking System",
  "Gearless Transmission Using Elbow Mechanism",
  "5 Speed Gearbox Mechanism",
  "Contactless Eddy Braking System",
  "Design & Fabrication of Motorized Scissor Jack",
  "Solar SeaWater Desalination Machine",
  "Portable 3 in 1 Car Washer & Wiper",
  "360 Degree Flexible Drilling Machine",
  "Hydraulic Flood Protection System for Homes",
  "Automatic Blackboard / Whiteboard Cleaner System",
  "Automated Drain/Gutter Cleaner Project",
  "Automated 5Dof Robotic Arm Mechanism",
  "Automatic MotorBike Stand Slider",
  "Portable Air Compressor with Auto Cutoff",
  "Design & Fabrication Of Mechanical Footstep Power Generator",
  "Mechanical Bird Flapping Mechanism",
  "Regenerative Braking System Project",
  "Motorized Power Steering Mechanism",
  "Four Wheel Steering Mechanism Project",
  "Theo Jansen Mechanism 4 Legs Spider Bot",
  "Automatic Motorized Bench Vise",
  "Hand Cranked Planetary Gearbox Mechanism",
  "Cam Shaft Mechanism DIY Ventilator",
  "Pneumatic Operated Double Hacksaw Project",
  "Automatic Pneumatic Hammer Machine Project",
  "Automatic Pneumatic Paper Cutting Machine Project",
  "Power Generator Forearms Machine",
  "Design and Fabrication of Automatic Pneumatic Ramming Machine",
  "Design and Fabrication of Emergency braking system in Four-Wheeler",
  "Design & Fabrication of V8 Engine",
  "Dual Axis Vehicle Steering Mechanism",
  "Leaf Spring Chassis for Construction Trucks",
  "Football Shooter Soccer Ball Launcher Machine",
  "Pneumatic Drone Catcher | Net Thrower",
  "Pneumatic Powered Mini Vibratory Conveyor",
  "Electrical Power Generation from Foot Step using 555 Timer IC",
  "Drill Press Project",
  "Table Saw Project",
  "Mini Mechanical Wire & Rod Cutter Machine",
  "Motorized Chain Mechanism Hacksaw",
  "Design and Fabrication of Bucket Conveyor",
  "DIY Automatic Screen Printing Machine",
  "Motorized Solar Scarecrow Bird Animal Repellent",
  "Chain Link Wire Mesh Making Machine",
  "DIY Scissor lift Shoes",
  "Manually operated Eco-friendly Road and Floor Dust Cleaning Machine",
  "Motorized Spring Assist Mashing Machine",
  "Reciprocating Motion using Inclined Disc Mechanism",
  "Inclined Cam Mechanism",
  "Pedal Operated Hacksaw",
  "Pedal Powered Electricity Generator Project",
  "Mini Conveyor Belt Mechanism",
  "Automatic Flipping Plate Mechanism",
  "Convex Surface Milling Machine",
  "Mechanical Pick & Place Mechanism",
  "Pedal Press Pneumatic Lifting Jack",
  "Reciprocating Auto Pneumatic Hacksaw",
  "4 Slot Coin Operated Cola Vending Machine",
  "Variable Head Solar Grass Cutter Weed Trimmer",
  "Automatic Sugarcane Bud Cutter Machine",
  "Wind & Solar Mobile Charging Station",
  "Flamethrower & Extinguisher RC Robot",
  "Floating Sun Tracker Hydraulic Solar Panel",
  "Mini Hacksaw Powered By Beam Engine",
  "Head Tilt Controlled Wheelchair for Disabled",
  "RC Solar Lake Pool Cleaner Drone",
  "Advanced Mosquito Killer Machine",
  "Three Axis CNC Machine 1 Meter x 2 Meter",
  "Oil Skimmer RC Boat",
  "Electromagnetic Coil Gun 3 Stage",
  "Airport Baggage Diverter System using QR",
  "Automatic Coil Winding Machine",
  "Off Road Adventure Robot with Action Camera",
  "Waterproof Action Camera Drone",
  "Solar Panel Cleaning Robot",
  "DIY Food Shredder Compost Machine",
  "Indoor Farming Hydroponic Plant Grow Tent",
  "Rain Sensing Hands Free Umbrella Bag",
  "Egg Breaker & Yolk Separator Machine",
  "Automatic Self Folding Dining Table",
  "RC Underwater Exploration Drone",
  "SeaWave Power Generator With Solar",
  "Wall Climbing Glass Cleaner Robot",
  "Motorized Paper Shredder Machine",
  "Sustainable Fishing Drone Without Bycatch",
  "Portable Electric Power Tiller Machine",
  "IOT Syringe Infusion Pump",
  "Self Charging Solar Powered Drone",
  "Auto IV Pole with IV Bag Refill Alert",
  "Pesticide Sprayer & COVID Sanitization Drone",
  "Thermal Vision RC Robotic Tank",
  "Programmable Robotic Arm Using Arduino",
  "IOT Virtual Doctor Robot",
  "Medical Supplies Delivery Drone",
  "Dual Side Potato Fries Maker Machine",
  "Motorized 4 Way Hacksaw",
  "Mattress Deep Cleaning Machine",
  "Automatic Potato Peeling Machine",
  "IOT Weather Station Airship",
  "Fishing Drone",
  "Electric Adventure Tour Bike",
  "Pneumatic Metal Sheet Bending Machine",
  "Indoor Racing Drone with Action Camera",
  "DIY Tricopter Selfie Drone",
  "Mini Belt Grinder Project",
  "Rough Terrain 3 Wheel Electric Bike",
  "Hydraulic Sheet Metal Bending Machine",
  "Zero Friction Electromagnetic Braking System Project",
  "All Weather Rain Proof Hubless Ebike",
  "Motorized Windshield Car & Bus Wiper Mechanism",
  "Unique Hubless Ebike With Suspension",
  "Anti Riot Shield With Pepper Spray & Blinding",
  "360° Aerial Surveillance UAV With IOT Camera",
  "Power Generation Using Electromagnetic Suspension",
  "360° Filmmaking Drone For 4K HD Video",
  "Solar Outdoor Air Purifier & Air Quality Monitor",
  "Fire Extinguisher & Fire Fighting Drone",
  "Semi Automatic Back Massager Machine",
  "Arm Mounted Hammer Drill Machine",
  "Pneumatic Arm Hammer Attachment With Nail Puller",
  "360° Welding Cutting Rotary Turn Table Positioner",
  "Indoor Farming Hydroponic Plant Grow Chamber",
  "Mini Conveyor using Geneva Mechanism",
  "Portable PPE Kit Sterilizer Ozone + UV",
  "Thermal Screening Drone",
  "Skin Safe Human Sanitization Tunnel",
  "Automatic Noodle Making Machine",
  "Dual Mount Auto Sanitizer Dispenser",
  "Auto Motorized Crispy Dosa Maker Machine",
  "Auto Indoor Hydroponic Fodder Grow Chamber",
  "Autonomous Theft Proof Delivery Robot For Food & Ecommerce",
  "Social Distancing & Mask Monitor Drone",
  "DIY Oxygen Concentrator Generator For Covid 19",
  "DIY Ventilator using Arduino For Covid Pandemic",
  "Design and Fabrication of External Pipe Climbing Robot",
  "Anti-Riot Drone with Tear Gas",
  "PLC based Automatic Sorting System using Image processing",
  "Electricity Generator Tiles Project",
  "Pneumatic Power Steering System",
  "Stress Analysis on Spur Gear Using Ansys",
  "Pneumatic Vibratory Screw Feeder Bowl",
  "Design and Fabrication of Dual Side Shaper Machine Project",
  "Automatic Bead Ball Bearing Sorting Machine",
  "Solenoid Engine Project",
  "Unlimited Battery E bike using Solar & Wind Power",
  "Three-wheeled High-Powered Mountain Climber E-bike",
  "Expandable Transforming Ebike 1 to 3 Seater",
  "Automatic Knock Detector Pneumatic Door Opener Using Peizo",
  "DIY 5DOF Wireless Hand Motion Controlled Robotic Gripper Arm",
  "Automatic Waste Segregation System",
  "Power Saving System for Lathe",
  "Design and Manufacturing of Solar Powered Seed Sprayer Machine",
  "Design and Fabrication of Mini Groundnut & Peanut Shelling Machine",
  "Air Powered Mini Wall Climbing Robot Project",
  "Design and Fabrication of Pedal Powered Washing Machine",
  "Modelling and Fabrication of Abrasive Jet Machine",
  "Mini Hydraulic Hand Operated JCB Crane",
  "20 Liter Jar Automatic Cleaning and Washing machine",
  "Design and Fabrication of Multipurpose Agricultural Machine",
  "Alcohol Detection with Go Kart Ignition Locking Project",
  "Design of Low-Cost Refrigeration System using LPG",
  "Kinetic Energy Recovery System using a Flywheel in Bicycle",
  "Car/Wheel Dollies using Hydraulic Ratchet Mechanism",
  "Pneumatic Reciprocating Power Hacksaw Machine Project",
  "Design and Fabrication of Pneumatic Bearing Puller Project",
  "Stirling Engine Project",
  "Battery Drive Motorized Agriculture Weeder",
  "Pneumatic Sand Filtering Project",
  "Pneumatic Paper Cup Making Machine Project",
  "Box Transport Mechanism Project",
  "360-Degree Rotating Vehicle",
  "Gear Based Quick Return Mechanism",
  "Pneumatic Powered Metal Pick and Place Arm",
  "Bench Tapping Machine",
  "E Skateboard With Motion Sensing",
  "Motorized Smart Turning Mechanism",
  "Pneumatic Powered Wall Climbing Robot",
  "Coin Based Cola & Soda Vending Machine",
  "Motorized Scotch Yoke Mechanism Piston",
  "Mini Windmill Power Generation Project",
  "3 DOF Hydraulic Extractor Mini JCB",
  "Steering Mechanism Vehicle With Joystick Control",
  "Bedini Wheel Using Electromagnetic Flux Generation",
  "Automatic Mechanical Garage Door Opener",
  "Automatic Paper Cutting Machine Using Geneva Mechanism",
  "Design & Fabrication of Automated Punching Machine",
  "2 Wheel Drive Forklift For Industry Warehouses",
  "Design & Fabrication of Attachable Wheelchair Automator",
  "Automated Portable Hammering Machine",
  "Automatic Seed Sowing Robot",
  "Faulty Product Detection And Separation System",
  "Dual Motor Electric Go-Kart For Rough Terrain",
  "Automated Coconut Scraping Machine",
  "Automated Double Hacksaw Project",
  "Pedal Powered Water Purifier Project",
  "Pulley Based Movable Crane Robot",
  "Push Based Box Transport Mechanism",
  "Rough Terrain Beetle Robot",
  "Smart Solar Grass Cutter With Lawn Coverage",
  "Single Stage Gear Reducer Project",
  "Torque Generator Mechanism",
  "High Performance Hovercraft With Power Turning",
  "Motorized 2 Wheel Scooter Project",
  "Fire Fighter Robot With Night Vision Camera",
  "Long Range Spy Robot With Night Vision",
  "Long Range Spy Robot With Obstacle Detection",
  "Long Range Spy Robot With Metal Detection",
  "Remote Controlled Automobile Using Rf",
  "Remote Controlled Robotic Arm Using Rf",
  "Android Controlled Robotic Arm",
  "Hand Motion Controlled Robotic Arm",
  "Hand Motion Controlled Robotic Vehicle",
  "Rf Controlled Spy Robot With Night Vision Camera",
  "Hovercraft Controlled By Android",
  "Fully Automated Solar Grass Cutter Robot",
  "Remote Controlled Pick & Place Robotic Vehicle",
  "MC Based Line Follower Robot",
  "Agricultural Robot Project",
  "Fire Fighter Robot Project",
  "RF Controlled Robotic Vehicle",
  "RF Controlled Robotic Vehicle With Metal Detection Project",
  "Obstacle Avoider Robotic Vehicle",
  "Voice Controlled Robotic Vehicle",
  "Advanced Footstep Power Generation System",
  "Coin Based Water Dispenser System"
];
