export const softwareProjectsList = [
  "AI-Powered Code Reviewer and Optimizer",
  "Distributed Key-Value Store with Raft Consensus",
  "Real-Time Collaborative Collaborative Canvas & Whiteboard",
  "Microservices Performance Monitoring & APM Dashboard",
  "Secure Zero-Knowledge Password Vault",
  "AI Meeting Notes Summarizer and Action Item Generator",
  "High-Performance Reverse Proxy and Load Balancer",
  "Serverless Vector Database Implementation",
  "Blockchain-Based Decentralized Identity Manager",
  "Git-Based Markdown Headless CMS",
  "Automated API Performance Design & Test Generator",
  "GraphQL to REST Adaptive Gateway Engine",
  "Container Orchestration Visualizer (Mini-Kubernetes)",
  "IoT Device Management and Real-Time Telemetry Dashboard",
  "End-to-End Encrypted File Sharing System",
  "Dynamic Database Schema Migration Tool",
  "Interactive Abstract Syntax Tree (AST) Visualizer",
  "Cloud-Native Distributed Task Scheduler",
  "Visual Git Conflict Resolution Workspace",
  "AI-Powered Smart Resume Tailor and Evaluator",
  "Cross-Platform Terminal-Based Code Editor",
  "Automated Database Clustering and Backup Orchestrator",
  "Real-time Audio Streaming and Transcription Server",
  "Automated Cloud Infrastructure Cost Optimizer",
  "Web3 Ethereum Wallet & Smart Contract Explorer",
  "AI-Driven Database Query Performance Tuner",
  "Distributed Web Crawler and Indexer Engine",
  "Self-Hosted Sentry-like Error Tracking System",
  "WebSockets-Based Multiplayer Canvas Game Engine",
  "Command Line Interface (CLI) Package Hub",
  "No-Code Visual Database Designer",
  "AI Bug Locator & Automatic PR Creator"
];
